version: '3.4'

services:

  browser:
    image: lscr.io/linuxserver/chromium:latest
    container_name: chromium
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CHROME_CLI=https://google.com/ #optional
      - CUSTOM_USER=treat
      - PASSWORD=${PASSWORD_BROWSER}
      - CUSTOM_PORT=4445
      - CUSTOM_HTTPS_PORT=4444
    volumes:
      - ./deluge/volumes/watch:/config/Downloads
    shm_size: "1gb"
    network_mode: service:vpn
    restart: unless-stopped

  vpn:
    image: dperson/openvpn-client
    container_name: ovpn

    cap_add:
      - NET_ADMIN

    read_only: true
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - label:disable

    stdin_open: true
    tty: true

    volumes:
      - /dev/net:/dev/net:z
      - ~/ovpns:/vpn
      # TODO: Write readme for ovpns
    environment:
      TZ: 'London/Europe'
    # TODO: Use ENV

    # * Note: Add port forwards here for services running behind the vpn 
    ports:
      - 8112:8112 # Deluge
      - 4444:4444 # Browser https
      - 4445:4445 # Browser http
    command: openvpn --config /vpn/treatfree.ovpn --askpass /vpn/treat_auth.txt
    # TODO: ENV file for --config and --askpass args + example

    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8010:8080
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
    depends_on:
      - jenkins-ssh-agent
    # network_mode: host

  jenkins-ssh-agent:
    image: jenkins/ssh-agent

  #** Torrent client container
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge

    # * Custom Dockerfile
    # build:
    #   context: ./deluge
    #   dockerfile: Dockerfile

    volumes:
      - ./deluge/volumes/config:/config
      - ./deluge/volumes/downloads:/downloads
      - ./deluge/volumes/watch:/watch
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=London/Europe
      # TODO: Use ENV
      # - DELUGE_LOGLEVEL=error # optional
    network_mode: service:vpn

    restart: unless-stopped
    depends_on:
      - vpn

  # Home Assistant
  hass:
    container_name: hass
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./hass/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  # Obsidian
  obsidian:
    image: 'ghcr.io/sytone/obsidian-remote:latest'
    container_name: obsidian-remote
    restart: unless-stopped
    ports:
      - 9620:9620
      - 9621:9621
    volumes:
      - ./obsidian/vaults:/vaults
      - ./obsidian/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=London/Europe
      - DOCKER_MODS=linuxserver/mods:universal-git
      - CUSTOM_PORT=9620
      - CUSTOM_HTTPS_PORT=9621 
      # - CUSTOM_USER=""
      # - PASSWORD=""
      # - SUBFOLDER=""

  # Doom
  doom:
    container_name: doom
    image: callumhoughton22/doom-in-docker:0.1
    restart: unless-stopped
    ports: 
      - 6660:8080

networks:
  pirate_net:
    driver: bridge

# TODO: Env file for timezone
